Repository KMU-WINK/workinkorea, pull requests merged in 2024-09, with the labels that each got.

#99 Fix: 메타데이터 수정(open graph 이미지 변경, metadataBase 추가)
  frontend/public/images/ogImage.png
  frontend/public/images/opengraph-image.png
  frontend/src/app/layout.tsx
Labels: 🐛 bug, 👏 enhancement, 🛠 Improving

#24 Feature: 소셜 로그인 구현(카카오, 네이버, 구글)
  backend/app/main.py
  backend/app/routers/auth.py
  commitlint.config.js
  frontend/src/app/layout.tsx
  frontend/src/app/sign-in/page.tsx
  frontend/src/components/KakaoScriptLoader/index.tsx
  frontend/src/types/kakao.d.ts
Labels: 👏 enhancement

#103 fix: `git-push.yml` 파일 수정
  .github/workflows/git-push.yml
Labels: 👏 enhancement, 🛠 Improving

#115 hotfix: build error 수정, 스플래시 스크린 처리 위치 변경
  frontend/public/sw.js
  frontend/src/app/layout.tsx
  frontend/src/components/ClientLoading/index.tsx
  frontend/src/components/SplashScreen/index.tsx
Labels: 🐛 bug

#118 Feature: 스플래시 화면 디자인 반영 및 적용 위치 변경
  frontend/next.config.js
  frontend/public/images/splash-image.svg
  frontend/public/sitemap-0.xml
  frontend/public/sw.js
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/ClientLoading/index.tsx
Labels: etc, 👏 enhancement, 🛠 Improving

#119 Hotfix: duplicated import 제거
  frontend/src/app/layout.tsx
Labels: 🐛 bug, 👏 enhancement

#120 Hotfix: favicon 미노출 에러 수정
  frontend/public/sitemap-0.xml
  frontend/public/sw.js
  frontend/src/app/favicon.ico
  frontend/src/app/layout.tsx
Labels: 🐛 bug

#122 Fix: favicon(파비콘) production 환경 미노출 에러 수정
  frontend/src/app/icon.ico
Labels: 🐛 bug

#124 Feature: 검색 페이지 개발
  frontend/public/svgs/character.svg
  frontend/public/svgs/dropdown.svg
  frontend/src/app/search/_components/DropDown/index.tsx
  frontend/src/app/search/_components/TrendList/index.tsx
  frontend/src/app/search/page.tsx
  frontend/tsconfig.json
Labels: 👏 enhancement

#126 Feature: spot and stay api
  frontend/public/images/spot-default.svg
  frontend/src/app/(detail)/_components/InfoItem.tsx
  frontend/src/app/(detail)/_utils/stringUtils.ts
  frontend/src/app/(detail)/layout.tsx
  frontend/src/app/(detail)/spot/[spotId]/page.tsx
  frontend/src/app/(detail)/stay/[stayId]/page.tsx
  frontend/src/app/(detail)/tour/[tourId]/page.tsx
  frontend/src/app/(feed)/layout.tsx
  frontend/src/app/(feed)/stay/page.tsx
  frontend/src/app/(feed)/tour/page.tsx
  frontend/src/services/publicAxiosInstance.ts
  frontend/src/types/type.ts
Labels: 👏 enhancement

#128 Fix: 검색 페이지 url 수정
  frontend/src/app/search/page.tsx
Labels: 🐛 bug

#130 feat: 토큰 검증 및 현재 사용자 가져오기 기능 추가
  backend/app/routers/auth.py
Labels: 👏 enhancement

#77 Feature: 온보딩 페이지 개발
  backend/app/models/User.py
  backend/app/routers/auth.py
  frontend/public/images/location/강릉.png
  frontend/public/images/location/경주.png
  frontend/public/images/location/부산.png
  frontend/public/images/location/여수.png
  frontend/public/images/location/전주.png
  frontend/public/images/location/제주.png
  frontend/public/images/location/춘천.png
  frontend/public/sitemap-0.xml
  frontend/public/sw.js
  frontend/src/app/(detail)/job/[jobId]/page.tsx
  frontend/src/app/(detail)/spot/[spotId]/page.tsx
  frontend/src/app/(feed)/layout.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/onboarding/_components/Badge/index.tsx
  frontend/src/app/onboarding/_components/Button/index.tsx
  frontend/src/app/onboarding/_components/ImageButton/index.tsx
  frontend/src/app/onboarding/layout.tsx
  frontend/src/app/onboarding/step1/page.tsx
  frontend/src/app/onboarding/step2/page.tsx
  frontend/src/app/onboarding/step3/page.tsx
  frontend/src/app/onboarding/step4/page.tsx
  frontend/src/app/onboarding/step5/page.tsx
  frontend/src/app/search/page.tsx
  frontend/src/app/sign-in/page.tsx
  frontend/src/app/wish/[id]/page.tsx
  frontend/src/app/wish/page.tsx
  frontend/src/components/Button/index.tsx
  frontend/src/components/Card/index.tsx
  frontend/src/components/DatePicker/index.tsx
  frontend/src/components/Input/index.tsx
  frontend/src/components/SelectButton/index.tsx
  frontend/src/services/publicAxiosInstance.ts
  frontend/src/types/type.ts
  frontend/tailwind.config.ts
Labels: 👏 enhancement

#131 Feature: job api
  frontend/next.config.js
  frontend/public/svgs/job-default.svg
  frontend/src/app/(detail)/_utils/stringUtils.ts
  frontend/src/app/(detail)/job/[jobId]/page.tsx
  frontend/src/app/(feed)/job/page.tsx
  frontend/src/app/(feed)/stay/page.tsx
  frontend/src/app/(feed)/tour/page.tsx
  frontend/src/app/utils/stringUtils.ts
  frontend/src/components/Card/index.tsx
  frontend/src/types/type.ts
Labels: 👏 enhancement

#135 fix: redirect CORS 에러 수정
  backend/app/routers/auth.py
  frontend/src/app/onboarding/step5/page.tsx
Labels: 🐛 bug

#138 Fix: `DatePicker` 컴포넌트 '삭제' 버튼 클릭 상황에 대한 예외 처리 추가
  frontend/public/sitemap-0.xml
  frontend/public/sw.js
  frontend/src/app/onboarding/step2/page.tsx
  frontend/src/components/DatePicker/index.tsx
Labels: 🐛 bug

#141 Feature: 로그인 모달 연결 작업
  backend/app/routers/auth.py
  frontend/package.json
  frontend/public/sitemap-0.xml
  frontend/public/sw.js
  frontend/src/app/(feed)/job/page.tsx
  frontend/src/app/(feed)/stay/page.tsx
  frontend/src/app/(feed)/tour/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/main/page.tsx
  frontend/src/app/sign-in/page.tsx
  frontend/src/app/stores/loginStore.ts
  frontend/src/app/stores/modalStore.ts
  frontend/src/components/Modals/LoginModal.tsx
  frontend/src/components/Modals/Modal.tsx
  frontend/yarn.lock
Labels: 👏 enhancement

#97 Feature: 탐색 지도 페이지 개발
  frontend/package-lock.json
  frontend/package.json
  frontend/public/svgs/ping-active.svg
  frontend/public/svgs/ping.svg
  frontend/src/app/layout.tsx
  frontend/src/app/map/page.tsx
  frontend/src/components/KakaoScriptLoader/map.tsx
  frontend/src/components/KakaoScriptLoader/sdk.tsx
  frontend/src/types/type.ts
  frontend/yarn.lock
Labels: 👏 enhancement

#156 Feature: setting 페이지 작업
  frontend/public/images/profile-default.jpg
  frontend/public/svgs/camera.svg
  frontend/src/app/onboarding/step1/page.tsx
  frontend/src/app/onboarding/step2/page.tsx
  frontend/src/app/onboarding/step3/page.tsx
  frontend/src/app/onboarding/step4/page.tsx
  frontend/src/app/onboarding/step5/page.tsx
  frontend/src/app/search/page.tsx
  frontend/src/app/setting/modify/page.tsx
  frontend/src/app/setting/modify/tour/page.tsx
  frontend/src/app/setting/page.tsx
  frontend/src/components/Button/index.tsx
  frontend/src/components/Content/index.tsx
  frontend/src/components/DropDown/index.tsx
  frontend/src/components/Header/index.tsx
  frontend/src/components/SmallButton/index.tsx
  frontend/src/services/users.ts
  frontend/src/types/user.ts
  frontend/src/utils/dateUtils.ts
Labels: 👏 enhancement

#173 hotfix: 토큰 심기 이후 Redirect에도 dev mode 분기 추가
  backend/app/routers/auth.py
Labels: 🐛 bug

#176 fix: 상용 환경, 테스트 환경 분기하여 쿠키 설정하도록 수정
  backend/app/routers/auth.py
Labels: 🐛 bug

#183 Feature: Feed 및 Detail Wish Api 연결
  frontend/src/app/(detail)/job/[jobId]/page.tsx
  frontend/src/app/(detail)/spot/[spotId]/page.tsx
  frontend/src/app/(feed)/_utils/stringUtils.ts
  frontend/src/app/(feed)/job/page.tsx
  frontend/src/app/(feed)/stay/page.tsx
  frontend/src/app/(feed)/tour/page.tsx
  frontend/src/services/jobs.ts
  frontend/src/services/spots.ts
  frontend/src/services/stays.ts
  frontend/src/services/wishs.ts
  frontend/src/types/type.ts
Labels: 👏 enhancement

#192 Hotfix: AccessToken 사용 방법 변경
  backend/app/routers/auth.py
  frontend/src/app/setting/modify/page.tsx
  frontend/src/app/setting/page.tsx
Labels: 🐛 bug, 📝 documentation, 🛠 Improving
