Repository KMU-WINK/workinkorea, pull requests merged in 2024-08, with the labels that each got.

#43 Feature: button component 구현
  frontend/src/components/Button/index.tsx
  frontend/src/components/SelectButton/index.tsx
Labels: 👏 enhancement

#45 Feature: card component 구현
  frontend/.eslintrc.json
  frontend/public/svgs/heart-fill.svg
  frontend/public/svgs/heart.svg
  frontend/src/components/Card/index.tsx
  frontend/src/types/type.ts
Labels: 👏 enhancement

#44 Feature : Modal Component 구현
  frontend/src/app/sign-in/_components/Modal.tsx
  frontend/src/app/sign-in/page.tsx
Labels: 👏 enhancement

#58 Feature: 배너 배경 이미지 추가
  frontend/src/app/main/_components/Banner/index.tsx
Labels: 👏 enhancement

#64 fix: card component - Image width height 추가
  frontend/src/components/Card/index.tsx
Labels: 👏 enhancement

#66 feat: layout.tsx - html 태그 배경 수정
  frontend/src/app/layout.tsx
Labels: 👏 enhancement

#67 Feature: 탐색 - 피드 페이지 개발
  frontend/public/svgs/feed-banner.svg
  frontend/public/svgs/feed-test.svg
  frontend/src/app/(feed)/job/page.tsx
  frontend/src/app/(feed)/layout.tsx
  frontend/src/app/(feed)/stay/page.tsx
Labels: 👏 enhancement

#70 Chore: Banner Type 분리
  frontend/src/app/main/_components/Banner/index.tsx
  frontend/src/types/type.ts
Labels: 👏 enhancement

#51 Feature: 탐색 - 세부 페이지 개발
  frontend/public/images/stay-test.png
  frontend/public/images/tour-test.png
  frontend/public/svgs/back-white.svg
  frontend/public/svgs/go-small.svg
  frontend/public/svgs/job-test.svg
  frontend/public/svgs/location.svg
  frontend/src/app/(detail)/job/[jobId]/page.tsx
  frontend/src/app/(detail)/layout.tsx
  frontend/src/app/(detail)/stay/[stayId]/page.tsx
  frontend/src/app/(detail)/tour/[tourId]/page.tsx
Labels: 👏 enhancement

#61 Feature: 메인 페이지 개발
  frontend/public/images/banner-test.jpg
  frontend/public/images/profile-test.png
  frontend/public/svgs/job-icon.svg
  frontend/public/svgs/stay-icon.svg
  frontend/public/svgs/tour-icon.svg
  frontend/src/app/main/_components/Banner/index.tsx
  frontend/src/app/main/page.tsx
  frontend/src/components/Input/index.tsx
Labels: 👏 enhancement

#80 Feature: 카드 컴포넌트 onclick 추가
  frontend/src/components/Card/index.tsx
  frontend/src/types/type.ts
Labels: 👏 enhancement

#81 Feature: next config 이미지 도메인 설정
  frontend/next.config.mjs
  frontend/src/components/Card/index.tsx
Labels: 👏 enhancement

#86 feat: Card map key 추가
  frontend/src/app/(feed)/stay/page.tsx
  frontend/src/app/(feed)/tour/page.tsx
Labels: 👏 enhancement

#89 fix: layout 겹침 현상 및 feed interface 수정
  frontend/src/app/(feed)/layout.tsx
  frontend/src/app/(feed)/stay/page.tsx
  frontend/src/app/(feed)/tour/page.tsx
  frontend/src/types/type.ts
Labels: 🐛 bug

#91 Feature: Next.js + Vercel CI/CD 설정 파일 추가(테스트)
  frontend/.eslintrc.json
  frontend/build.sh
  frontend/src/app/(feed)/job/page.tsx
  frontend/src/app/main/page.tsx
  frontend/src/app/wish/[id]/page.tsx
  frontend/src/components/Card/index.tsx
Labels: 👏 enhancement, 🛠 Improving

#82 Feature: Next.js 검색 엔진 최적화(SEO) 작업
  frontend/next-sitemap.config.js
  frontend/package.json
  frontend/public/images/ogImage.png
  frontend/public/robots.txt
  frontend/public/sitemap-0.xml
  frontend/public/sitemap.xml
  frontend/src/app/layout.tsx
  frontend/yarn.lock
Labels: 👏 enhancement, 🛠 Improving
