Repository KMU-WINK/workinkorea, pull requests merged in 2024-07, with the labels that each got.

#10 chore: `nvm` 설정 관련 파일 추가 및 `README.md` 업데이트
  frontend/.nvmrc
  frontend/README.md
  frontend/yarn.lock
Labels: 👏 enhancement, 📝 documentation

#25 Chore: Figma SVG 추출
  frontend/public/svgs/back.svg
  frontend/public/svgs/calender.svg
  frontend/public/svgs/close.svg
  frontend/public/svgs/filter.svg
  frontend/public/svgs/go.svg
  frontend/public/svgs/google.svg
  frontend/public/svgs/heart-color.svg
  frontend/public/svgs/heart-fill.svg
  frontend/public/svgs/heart.svg
  frontend/public/svgs/index.ts
  frontend/public/svgs/kakao.svg
  frontend/public/svgs/map.svg
  frontend/public/svgs/naver.svg
  frontend/public/svgs/search.svg
  frontend/public/svgs/setting-color.svg
  frontend/public/svgs/setting-fill.svg
  frontend/public/svgs/setting.svg
Labels: 👏 enhancement

#38 Fix: tailwind config colors 이슈 해결
  frontend/tailwind.config.ts
Labels: 🐛 bug
